//Use of a Global Reg Var (a GCC extension to C language).
//illustrated for Intel 686, running linux.
//see the assembly version (ass generated by gcc -S)-- interesting.

register int foo asm("esi");  //declare 'foo' as a global reg var

int main(void)
{
    int bar;
    foo = 1;  //initialize global variable 'foo'
    bar = foo + 5;  //use 'foo'
    printf("bar = %d\n", bar);
    return 0;
}

