#! /bin/csh -f

# this script expects a command (name and arguments) as its arguments.
# it executes the command, suppresses its stderr and copies its 
# stdout to stdout, so that
# only the stdout of the command can be redirected to a file or piped to
# another command or viewed on screen.
# caveat: the script works in a subshell, which does not inherit the
# aliases of the parent shell. also note that 'bash' won't recognize
# the C-shell built-ins.

bash -c "($*) 2> /dev/null"

