#!/bin/tcsh -f

#uses 'gid32' to find the definition of a function
#in Cisco IOS codebase.
#argument: name of the function whose definition needs to be found.
#Opens gvim with cursor positioned at the beginning of the 
#function definition.
#Expects a clearcase view with ID built.
#Finding definition of a function is a little hackish:
#expects 1. function has exacly one definition
# 2. the definition begins with <func-name><space><left-parenthesis>

set defloc = `gid32 $1 | grep "$1 ("`
echo "$defloc"

set filename = `echo "$defloc" | cut -f 1 -d ':'`
set linenum = `echo "$defloc" | cut -f 2 -d ':'`

gvim "+$linenum" $filename

